import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { CardProd } from "../components/Card";
import { Container } from "@mui/system";
import { Box } from "@mui/material";

const Home: NextPage = ({ products }: any) => {
  return (
    <Container component="div">
      <Head>
        <title>E-Commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component="div" className={styles.main}>
        <Container component="div" className={styles.container}>
          <Box component="div" className={styles.row}>
            <CardProd product={products.products} />
          </Box>
        </Container>
      </Box>
    </Container>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const req = await fetch(`https://dummyjson.com/products`);
  const data = await req.json();
  return {
    props: {
      products: data,
    },
  };
};
